// src/gvrm-format/uv-decoder.ts
// GUAVA UV Decoder - WebGL GPU専用版（事前計算マッピング不要）
// 修正版: 入力検証・CHWインデックス計算・エラーハンドリング強化

import * as ort from 'onnxruntime-web/wasm';
import type { UVTriangleMapping } from './webgl-uv-rasterizer';

/**
 * UV Gaussians の出力データ構造
 */
export interface UVGaussianOutput {
  uvCount: number;
  
  // モデル出力（UV空間）
  localPositions: Float32Array;    // [N, 3] Δμ（三角形内ローカル位置）
  opacity: Float32Array;           // [N] α（不透明度）
  scale: Float32Array;             // [N, 3] s（スケール x,y,z）
  rotation: Float32Array;          // [N, 4] r（回転 quaternion）
  latent32ch: Float32Array;        // [N, 32] c（32次元特徴）
  
  // マッピングデータ（三角形への対応付け）
  triangleIndices: Uint32Array;    // [N] 各UV Gaussianが属する三角形
  barycentricCoords: Float32Array; // [N, 3] 重心座標
  uvCoords: Float32Array;          // [N, 2] UV座標（参照用）
}

/**
 * 配列検証結果
 */
interface ArrayValidation {
  length: number;
  nanCount: number;
  infCount: number;
  zeroCount: number;
  nanRatio: number;
  zeroRatio: number;
  min: number;
  max: number;
}

/**
 * UV Decoder（WebGL GPU専用版）
 * 
 * 変更点:
 * - 事前計算されたマッピングファイルの読み込みを削除
 * - WebGLラスタライザからのマッピングを直接受け取る
 * - 初期化が高速化
 * - 入力/出力の検証を強化
 * - CHW形式のインデックス計算を明示化
 */
export class UVDecoder {
  private session: ort.InferenceSession | null = null;
  private mapping: UVTriangleMapping | null = null;
  
  /**
   * 初期化（事前計算マッピング不要）
   */
  async init(basePath: string): Promise<void> {
    console.log('[UVDecoder] Initializing (WebGL GPU mode)...');
    
    try {
      // ONNX Runtime の設定
      ort.env.wasm.numThreads = 1;
      ort.env.wasm.simd = true;
      ort.env.wasm.proxy = false;
      
      // iOS対応の設定
      if (/iPad|iPhone|iPod/.test(navigator.userAgent)) {
        ort.env.wasm.numThreads = 1;
        ort.env.wasm.simd = false;
      }
      
      // モデルをロード
      const modelPath = `${basePath}/uv_point_decoder.onnx`;
      console.log('[UVDecoder] Loading model from:', modelPath);
      
      this.session = await ort.InferenceSession.create(modelPath, {
        executionProviders: ['wasm'],
        graphOptimizationLevel: 'all'
      });
      
      console.log('[UVDecoder] ✅ Model loaded');
      console.log('[UVDecoder] 🔍 Input names:', this.session.inputNames);
      console.log('[UVDecoder] 🔍 Output names:', this.session.outputNames);
      console.log('[UVDecoder] ⚡ UV Triangle Mapping will be generated by WebGL GPU');
      console.log('[UVDecoder] ✅ Initialization complete');
      
    } catch (error) {
      console.error('[UVDecoder] ❌ Initialization failed:', error);
      throw error;
    }
  }
  
  /**
   * マッピングを設定（WebGLラスタライザから受け取る）
   */
  setMapping(mapping: UVTriangleMapping): void {
    this.mapping = mapping;
    console.log('[UVDecoder] Mapping set:', {
      resolution: `${mapping.width}×${mapping.height}`,
      validPixels: mapping.numValid.toLocaleString(),
      coverage: `${(mapping.numValid / (mapping.width * mapping.height) * 100).toFixed(1)}%`
    });
  }
  
  /**
   * UV Gaussians を生成（マッピングを引数で受け取る版）
   * 
   * @param uvFeatureMap UV空間の特徴マップ [155, H, W]
   * @param uvWidth UV幅
   * @param uvHeight UV高さ
   * @param mapping WebGLラスタライザで生成されたマッピング
   * @returns UV Gaussians の属性データ
   */
  async generate(
    uvFeatureMap: Float32Array,
    uvWidth: number,
    uvHeight: number,
    mapping?: UVTriangleMapping
  ): Promise<UVGaussianOutput> {
    if (!this.session) {
      throw new Error('UVDecoder not initialized');
    }
    
    // マッピングを設定（引数または事前設定）
    if (mapping) {
      this.setMapping(mapping);
    }
    
    if (!this.mapping) {
      throw new Error('UV Triangle Mapping not provided. Use setMapping() or pass as argument.');
    }
    
    console.log('[UVDecoder] Generating UV Gaussians...');
    
    // ✅ 入力検証を強化
    const expectedSize = 155 * uvWidth * uvHeight;
    
    console.log('[UVDecoder] Input validation:', {
      uvFeatureMapSize: uvFeatureMap.length.toLocaleString(),
      expectedSize: expectedSize.toLocaleString(),
      uvResolution: `${uvWidth}×${uvHeight}`,
      match: uvFeatureMap.length === expectedSize ? '✅' : '❌'
    });
    
    // ✅ サイズチェック
    if (uvFeatureMap.length !== expectedSize) {
      throw new Error(
        `UV feature map size mismatch: expected ${expectedSize}, got ${uvFeatureMap.length}`
      );
    }
    
    // ✅ NaN/Inf/Zero チェック（サンプリング）
    const sampleSize = Math.min(10000, uvFeatureMap.length);
    let nanCount = 0;
    let infCount = 0;
    let zeroCount = 0;
    
    for (let i = 0; i < sampleSize; i++) {
      const v = uvFeatureMap[i];
      if (isNaN(v)) nanCount++;
      else if (!isFinite(v)) infCount++;
      else if (v === 0) zeroCount++;
    }
    
    const nanRatio = nanCount / sampleSize;
    const zeroRatio = zeroCount / sampleSize;
    
    console.log('[UVDecoder] Input quality check (first 10k values):', {
      nanCount,
      infCount,
      zeroCount,
      validCount: sampleSize - nanCount - infCount - zeroCount,
      nanRatio: (nanRatio * 100).toFixed(1) + '%',
      zeroRatio: (zeroRatio * 100).toFixed(1) + '%'
    });
    
    if (nanRatio > 0.5) {
      console.error('[UVDecoder] ❌ Input contains >50% NaN values!');
      console.error('[UVDecoder] This indicates Inverse Texture Mapping failed.');
      throw new Error('Invalid UV feature map: too many NaN values');
    }
    
    if (infCount > 0) {
      console.error('[UVDecoder] ❌ Input contains Infinity values!');
      throw new Error('Invalid UV feature map: contains Inf values');
    }
    
    if (zeroRatio > 0.9) {
      console.warn('[UVDecoder] ⚠️  Input is mostly zeros (>90%)!');
      console.warn('[UVDecoder] Output quality may be poor.');
    }
    
    try {
      // 入力テンソルを作成 [1, 155, H, W]
      const inputTensor = new ort.Tensor(
        'float32',
        uvFeatureMap,
        [1, 155, uvHeight, uvWidth]
      );
      
      const feeds = {
        'uv_features': inputTensor
      };
      
      // 推論実行
      console.log('[UVDecoder] Running inference...');
      const startTime = performance.now();
      
      const outputs = await this.session.run(feeds);
      
      const inferenceTime = performance.now() - startTime;
      console.log('[UVDecoder] ✅ Inference complete:', `${inferenceTime.toFixed(1)}ms`);
      
      // ✅ 利用可能な出力名を確認
      const availableOutputs = Object.keys(outputs);
      console.log('[UVDecoder] Available outputs:', availableOutputs);
      
      // 出力を取得
      const localPos = this.extractOutput(outputs, ['local_pos'], 3 * uvHeight * uvWidth);
      const opacity = this.extractOutput(outputs, ['opacity'], uvHeight * uvWidth);
      const scale = this.extractOutput(outputs, ['scale'], 3 * uvHeight * uvWidth);
      const rotation = this.extractOutput(outputs, ['rotation'], 4 * uvHeight * uvWidth);
      const color = this.extractOutput(outputs, ['color'], 32 * uvHeight * uvWidth);
      
      // ✅ 出力検証
      console.log('[UVDecoder] Validating outputs...');
      const outputValidation = {
        localPos: this.validateArray(localPos),
        opacity: this.validateArray(opacity),
        scale: this.validateArray(scale),
        rotation: this.validateArray(rotation),
        color: this.validateArray(color)
      };
      
      console.log('[UVDecoder] Output validation:');
      console.log('  localPos:', {
        nanRatio: (outputValidation.localPos.nanRatio * 100).toFixed(1) + '%',
        range: `[${outputValidation.localPos.min.toFixed(3)}, ${outputValidation.localPos.max.toFixed(3)}]`
      });
      console.log('  opacity:', {
        nanRatio: (outputValidation.opacity.nanRatio * 100).toFixed(1) + '%',
        range: `[${outputValidation.opacity.min.toFixed(3)}, ${outputValidation.opacity.max.toFixed(3)}]`
      });
      console.log('  scale:', {
        nanRatio: (outputValidation.scale.nanRatio * 100).toFixed(1) + '%',
        range: `[${outputValidation.scale.min.toFixed(3)}, ${outputValidation.scale.max.toFixed(3)}]`
      });
      console.log('  rotation:', {
        nanRatio: (outputValidation.rotation.nanRatio * 100).toFixed(1) + '%',
        range: `[${outputValidation.rotation.min.toFixed(3)}, ${outputValidation.rotation.max.toFixed(3)}]`
      });
      
      // すべてがNaNの場合はエラー
      if (outputValidation.localPos.nanRatio > 0.99) {
        throw new Error('UV Decoder output is all NaN - model inference failed');
      }
      
      // [B, C, H, W] → [N, C] への変換
      const uvGaussians = this.convertToGaussians(
        new Float32Array(localPos),
        new Float32Array(opacity),
        new Float32Array(scale),
        new Float32Array(rotation),
        new Float32Array(color),
        uvWidth,
        uvHeight
      );
      
      console.log('[UVDecoder] ✅ UV Gaussians generated:', {
        count: uvGaussians.uvCount.toLocaleString(),
        hasTriangleData: uvGaussians.triangleIndices.length > 0,
        hasBarycentricCoords: uvGaussians.barycentricCoords.length > 0
      });
      
      return uvGaussians;
      
    } catch (error) {
      console.error('[UVDecoder] ❌ Generation failed:', error);
      throw error;
    }
  }
  
  /**
   * 出力テンソルから配列を抽出
   * 修正版: エラーハンドリングを強化
   */
  private extractOutput(
    outputs: any,
    candidateNames: string[],
    expectedLength: number
  ): number[] {
    // ✅ 利用可能な出力名を確認
    const availableNames = Object.keys(outputs);
    
    for (const name of candidateNames) {
      if (outputs[name]) {
        const data = Array.from(outputs[name].data);
        
        // ✅ サイズ検証
        if (data.length !== expectedLength) {
          console.warn(
            `[UVDecoder] ⚠️  Output '${name}' size mismatch: ` +
            `expected ${expectedLength}, got ${data.length}`
          );
        }
        
        // ✅ 品質チェック（サンプリング）
        const sampleSize = Math.min(1000, data.length);
        const nanCount = data.slice(0, sampleSize).filter(v => isNaN(v)).length;
        
        if (nanCount > 0) {
          const nanRatio = (nanCount / sampleSize * 100).toFixed(1);
          console.warn(
            `[UVDecoder] ⚠️  Output '${name}' contains NaN values ` +
            `(${nanRatio}% in first ${sampleSize} values)`
          );
        }
        
        return data;
      }
    }
    
    // ✅ 出力が見つからない場合はエラー
    console.error('[UVDecoder] ❌ Output not found!');
    console.error('[UVDecoder]   Searched for:', candidateNames);
    console.error('[UVDecoder]   Available outputs:', availableNames);
    
    throw new Error(
      `Required output not found: ${candidateNames.join(', ')}. ` +
      `Available: ${availableNames.join(', ')}`
    );
  }
  
  /**
   * 配列の妥当性を検証
   */
  private validateArray(data: number[]): ArrayValidation {
    let nanCount = 0;
    let infCount = 0;
    let zeroCount = 0;
    let min = Infinity;
    let max = -Infinity;
    
    for (let i = 0; i < data.length; i++) {
      const v = data[i];
      if (isNaN(v)) {
        nanCount++;
      } else if (!isFinite(v)) {
        infCount++;
      } else {
        if (v === 0) zeroCount++;
        if (v < min) min = v;
        if (v > max) max = v;
      }
    }
    
    return {
      length: data.length,
      nanCount,
      infCount,
      zeroCount,
      nanRatio: nanCount / data.length,
      zeroRatio: zeroCount / data.length,
      min: isFinite(min) ? min : 0,
      max: isFinite(max) ? max : 0
    };
  }
  
  /**
   * [B, C, H, W] 形式の出力を [N, C] 形式のGaussiansに変換
   * 修正版: CHW形式のインデックス計算を明示的に
   */
  private convertToGaussians(
    localPos: Float32Array,
    opacity: Float32Array,
    scale: Float32Array,
    rotation: Float32Array,
    color: Float32Array,
    uvWidth: number,
    uvHeight: number
  ): UVGaussianOutput {
    console.log('[UVDecoder] Converting to Gaussians...');
    
    if (!this.mapping) {
      throw new Error('Mapping not loaded');
    }
    
    const numValid = this.mapping.numValid;
    
    // ✅ データ形式の検証を追加
    const expectedLocalPosSize = 3 * uvHeight * uvWidth;
    const expectedOpacitySize = uvHeight * uvWidth;
    const expectedScaleSize = 3 * uvHeight * uvWidth;
    const expectedRotationSize = 4 * uvHeight * uvWidth;
    const expectedColorSize = 32 * uvHeight * uvWidth;
    
    console.log('[UVDecoder] Expected vs Actual sizes:', {
      localPos: { expected: expectedLocalPosSize, actual: localPos.length },
      opacity: { expected: expectedOpacitySize, actual: opacity.length },
      scale: { expected: expectedScaleSize, actual: scale.length },
      rotation: { expected: expectedRotationSize, actual: rotation.length },
      color: { expected: expectedColorSize, actual: color.length }
    });
    
    // ✅ サイズ検証
    if (localPos.length !== expectedLocalPosSize) {
      console.error('[UVDecoder] ❌ LocalPos size mismatch!');
    }
    if (opacity.length !== expectedOpacitySize) {
      console.error('[UVDecoder] ❌ Opacity size mismatch!');
    }
    if (scale.length !== expectedScaleSize) {
      console.error('[UVDecoder] ❌ Scale size mismatch!');
    }
    if (rotation.length !== expectedRotationSize) {
      console.error('[UVDecoder] ❌ Rotation size mismatch!');
    }
    if (color.length !== expectedColorSize) {
      console.error('[UVDecoder] ❌ Color size mismatch!');
    }
    
    // 出力配列を確保
    const localPositions = new Float32Array(numValid * 3);
    const opacityOut = new Float32Array(numValid);
    const scaleOut = new Float32Array(numValid * 3);
    const rotationOut = new Float32Array(numValid * 4);
    const latent32ch = new Float32Array(numValid * 32);
    const triangleIndices = new Uint32Array(numValid);
    const barycentricCoords = new Float32Array(numValid * 3);
    const uvCoords = new Float32Array(numValid * 2);
    
    // ✅ CHW形式のインデックス計算ヘルパー
    const getChannelValue = (
      data: Float32Array,
      channel: number,
      y: number,
      x: number,
      numChannels: number
    ): number => {
      // CHW形式: index = channel * H * W + y * W + x
      const spatialSize = uvHeight * uvWidth;
      const idx = channel * spatialSize + y * uvWidth + x;
      
      if (idx >= data.length) {
        console.warn(`[UVDecoder] Index out of bounds: ${idx} >= ${data.length}`);
        return 0;
      }
      
      const value = data[idx];
      return isNaN(value) ? 0 : value;
    };
    
    // マッピングに従ってデータを抽出
    console.log('[UVDecoder] Extracting valid pixels...');

    // マッピングの解像度とUV特徴マップの解像度が異なる場合のスケール
    const mappingWidth = this.mapping.width;
    const mappingHeight = this.mapping.height;
    const scaleU = uvWidth / mappingWidth;
    const scaleV = uvHeight / mappingHeight;

    console.log('[UVDecoder] Resolution scaling:', {
      mapping: `${mappingWidth}×${mappingHeight}`,
      features: `${uvWidth}×${uvHeight}`,
      scale: `${scaleU.toFixed(3)}×${scaleV.toFixed(3)}`
    });

    let invalidCoordCount = 0;

    for (let i = 0; i < numValid; i++) {
      // マッピング座標をUV特徴マップ座標にスケーリング
      const uOrig = this.mapping.uvCoords[i * 2 + 0];
      const vOrig = this.mapping.uvCoords[i * 2 + 1];
      const u = Math.floor(uOrig * scaleU);
      const v = Math.floor(vOrig * scaleV);

      // ✅ 座標検証
      if (u >= uvWidth || v >= uvHeight || u < 0 || v < 0) {
        if (invalidCoordCount < 10) {
          console.warn(`[UVDecoder] Invalid UV coords at ${i}: (${uOrig}, ${vOrig}) → (${u}, ${v})`);
        }
        invalidCoordCount++;
        continue;
      }
      
      // Local Position (3ch)
      localPositions[i * 3 + 0] = getChannelValue(localPos, 0, v, u, 3);
      localPositions[i * 3 + 1] = getChannelValue(localPos, 1, v, u, 3);
      localPositions[i * 3 + 2] = getChannelValue(localPos, 2, v, u, 3);
      
      // Opacity (1ch)
      opacityOut[i] = getChannelValue(opacity, 0, v, u, 1);
      
      // Scale (3ch)
      scaleOut[i * 3 + 0] = getChannelValue(scale, 0, v, u, 3);
      scaleOut[i * 3 + 1] = getChannelValue(scale, 1, v, u, 3);
      scaleOut[i * 3 + 2] = getChannelValue(scale, 2, v, u, 3);
      
      // Rotation (4ch)
      rotationOut[i * 4 + 0] = getChannelValue(rotation, 0, v, u, 4);
      rotationOut[i * 4 + 1] = getChannelValue(rotation, 1, v, u, 4);
      rotationOut[i * 4 + 2] = getChannelValue(rotation, 2, v, u, 4);
      rotationOut[i * 4 + 3] = getChannelValue(rotation, 3, v, u, 4);
      
      // Color/Latent (32ch)
      for (let c = 0; c < 32; c++) {
        latent32ch[i * 32 + c] = getChannelValue(color, c, v, u, 32);
      }
      
      // Triangle データ
      triangleIndices[i] = this.mapping.triangleIndices[i];
      barycentricCoords[i * 3 + 0] = this.mapping.barycentricCoords[i * 3 + 0];
      barycentricCoords[i * 3 + 1] = this.mapping.barycentricCoords[i * 3 + 1];
      barycentricCoords[i * 3 + 2] = this.mapping.barycentricCoords[i * 3 + 2];
      
      // UV座標（正規化）
      uvCoords[i * 2 + 0] = u / uvWidth;
      uvCoords[i * 2 + 1] = v / uvHeight;
    }
    
    if (invalidCoordCount > 0) {
      console.warn(`[UVDecoder] ⚠️  Found ${invalidCoordCount} invalid UV coordinates`);
    }
    
    console.log('[UVDecoder] ✅ Conversion complete');
    
    // 統計情報を表示
    this.logStatistics('LocalPositions', localPositions, 3);
    this.logStatistics('Opacity', opacityOut, 1);
    this.logStatistics('Scale', scaleOut, 3);
    this.logStatistics('Rotation', rotationOut, 4);
    this.logStatistics('Latent32ch', latent32ch, 32);
    
    return {
      uvCount: numValid,
      localPositions,
      opacity: opacityOut,
      scale: scaleOut,
      rotation: rotationOut,
      latent32ch,
      triangleIndices,
      barycentricCoords,
      uvCoords
    };
  }
  
  /**
   * 統計情報をログ出力（デバッグ用）
   */
  private logStatistics(name: string, data: Float32Array, channels: number): void {
    let min = Infinity;
    let max = -Infinity;
    let sum = 0;
    let nanCount = 0;
    let validCount = 0;
    
    for (let i = 0; i < data.length; i++) {
      const val = data[i];
      if (isNaN(val)) {
        nanCount++;
        continue;
      }
      if (val < min) min = val;
      if (val > max) max = val;
      sum += val;
      validCount++;
    }
    
    const mean = validCount > 0 ? sum / validCount : 0;
    
    console.log(`[UVDecoder] ${name}:`, {
      shape: `[${data.length / channels}, ${channels}]`,
      min: isFinite(min) ? min.toFixed(4) : 'N/A',
      max: isFinite(max) ? max.toFixed(4) : 'N/A',
      mean: mean.toFixed(4),
      nanCount
    });
  }
}
